### ISSUE TITLE
Failed when build and run!

### ISSUE THREAD

**Issue by WillRRRR** [AcroMace/DreamBig#1]
I tried build and run on my iPad Pro 12.9" (1st gen/Space Gray/128GB/Wi-Fi) because It's error!
<img width="1144" alt="screen shot 2017-07-22 at 2 14 17 pm" src="https://user-images.githubusercontent.com/30376565/28494025-2bb3f46e-6ee8-11e7-8e32-0941c31e2d3f.png">

**Comment by AcroMace** [comment]
Hey Will, could you check which Xcode version you are using? These lines should be supported from Xcode 9 beta 2 onwards (but not in beta 1).

**Comment by AcroMace** [comment]
@WillRRRR Hey Will! Have you had any luck running on a later version of Xcode?
